export const FETCH_DATA = 'FETCH_DATA';
export const DONE_FETCHING_DATA = 'DONE_FETCHING_DATA';
export const ERROR_FETCHING_DATA = 'ERROR_FETCHING_DATA';
export const FETCH_PATTERN = 'FETCH_PATTERN';
export const DONE_FETCHING_PATTERN = 'DONE_FETCHING_PATTERN';
export const ERROR_FETCHING_PATTERN = 'ERROR_FETCHING_PATTERN';
